//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HypersDesktopWFApp.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeProduct", Namespace="http://schemas.datacontract.org/2004/07/HypersWebshop.ServiceLib")]
    [System.SerializableAttribute()]
    public partial class CompositeProduct : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HypersDesktopWFApp.ServiceReference1.Product_Description ProductDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HypersDesktopWFApp.ServiceReference1.Product_Status Product_StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long PurchasePriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HypersDesktopWFApp.ServiceReference1.Product_Description ProductDescription {
            get {
                return this.ProductDescriptionField;
            }
            set {
                if ((this.ProductDescriptionField.Equals(value) != true)) {
                    this.ProductDescriptionField = value;
                    this.RaisePropertyChanged("ProductDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HypersDesktopWFApp.ServiceReference1.Product_Status Product_Status {
            get {
                return this.Product_StatusField;
            }
            set {
                if ((this.Product_StatusField.Equals(value) != true)) {
                    this.Product_StatusField = value;
                    this.RaisePropertyChanged("Product_Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long PurchasePrice {
            get {
                return this.PurchasePriceField;
            }
            set {
                if ((this.PurchasePriceField.Equals(value) != true)) {
                    this.PurchasePriceField = value;
                    this.RaisePropertyChanged("PurchasePrice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product_Description", Namespace="http://schemas.datacontract.org/2004/07/HypersWebshop.Domain")]
    public enum Product_Description : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Harddisk = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RAM = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Batteri = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Strømforsyning = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GPU = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CPU_Køling = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Motherboard = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CPU = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Optisk_Drev = 8,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product_Status", Namespace="http://schemas.datacontract.org/2004/07/HypersWebshop.Domain")]
    public enum Product_Status : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sold = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Published = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unpublished = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Tested = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Untested = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rejected = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IProductService")]
    public interface IProductService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/CreateProduct", ReplyAction="http://tempuri.org/IProductService/CreateProductResponse")]
        int CreateProduct(HypersDesktopWFApp.ServiceReference1.CompositeProduct composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/CreateProduct", ReplyAction="http://tempuri.org/IProductService/CreateProductResponse")]
        System.Threading.Tasks.Task<int> CreateProductAsync(HypersDesktopWFApp.ServiceReference1.CompositeProduct composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/FindProduct", ReplyAction="http://tempuri.org/IProductService/FindProductResponse")]
        HypersDesktopWFApp.ServiceReference1.CompositeProduct FindProduct(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/FindProduct", ReplyAction="http://tempuri.org/IProductService/FindProductResponse")]
        System.Threading.Tasks.Task<HypersDesktopWFApp.ServiceReference1.CompositeProduct> FindProductAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/FindProductsByDescription", ReplyAction="http://tempuri.org/IProductService/FindProductsByDescriptionResponse")]
        System.Collections.Generic.List<HypersDesktopWFApp.ServiceReference1.CompositeProduct> FindProductsByDescription(HypersDesktopWFApp.ServiceReference1.Product_Description description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/FindProductsByDescription", ReplyAction="http://tempuri.org/IProductService/FindProductsByDescriptionResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<HypersDesktopWFApp.ServiceReference1.CompositeProduct>> FindProductsByDescriptionAsync(HypersDesktopWFApp.ServiceReference1.Product_Description description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/FindProductsByStatus", ReplyAction="http://tempuri.org/IProductService/FindProductsByStatusResponse")]
        System.Collections.Generic.List<HypersDesktopWFApp.ServiceReference1.CompositeProduct> FindProductsByStatus(HypersDesktopWFApp.ServiceReference1.Product_Status status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/FindProductsByStatus", ReplyAction="http://tempuri.org/IProductService/FindProductsByStatusResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<HypersDesktopWFApp.ServiceReference1.CompositeProduct>> FindProductsByStatusAsync(HypersDesktopWFApp.ServiceReference1.Product_Status status);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductServiceChannel : HypersDesktopWFApp.ServiceReference1.IProductService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductServiceClient : System.ServiceModel.ClientBase<HypersDesktopWFApp.ServiceReference1.IProductService>, HypersDesktopWFApp.ServiceReference1.IProductService {
        
        public ProductServiceClient() {
        }
        
        public ProductServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CreateProduct(HypersDesktopWFApp.ServiceReference1.CompositeProduct composite) {
            return base.Channel.CreateProduct(composite);
        }
        
        public System.Threading.Tasks.Task<int> CreateProductAsync(HypersDesktopWFApp.ServiceReference1.CompositeProduct composite) {
            return base.Channel.CreateProductAsync(composite);
        }
        
        public HypersDesktopWFApp.ServiceReference1.CompositeProduct FindProduct(int id) {
            return base.Channel.FindProduct(id);
        }
        
        public System.Threading.Tasks.Task<HypersDesktopWFApp.ServiceReference1.CompositeProduct> FindProductAsync(int id) {
            return base.Channel.FindProductAsync(id);
        }
        
        public System.Collections.Generic.List<HypersDesktopWFApp.ServiceReference1.CompositeProduct> FindProductsByDescription(HypersDesktopWFApp.ServiceReference1.Product_Description description) {
            return base.Channel.FindProductsByDescription(description);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<HypersDesktopWFApp.ServiceReference1.CompositeProduct>> FindProductsByDescriptionAsync(HypersDesktopWFApp.ServiceReference1.Product_Description description) {
            return base.Channel.FindProductsByDescriptionAsync(description);
        }
        
        public System.Collections.Generic.List<HypersDesktopWFApp.ServiceReference1.CompositeProduct> FindProductsByStatus(HypersDesktopWFApp.ServiceReference1.Product_Status status) {
            return base.Channel.FindProductsByStatus(status);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<HypersDesktopWFApp.ServiceReference1.CompositeProduct>> FindProductsByStatusAsync(HypersDesktopWFApp.ServiceReference1.Product_Status status) {
            return base.Channel.FindProductsByStatusAsync(status);
        }
    }
}
