//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HypersWebApp.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeProduct", Namespace="http://schemas.datacontract.org/2004/07/HypersWebshop.ServiceLib")]
    [System.SerializableAttribute()]
    public partial class CompositeProduct : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HypersWebApp.ServiceReference1.Product_Description ProductDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HypersWebApp.ServiceReference1.Product_Status Product_StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long PurchasePriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HypersWebApp.ServiceReference1.Product_Description ProductDescription {
            get {
                return this.ProductDescriptionField;
            }
            set {
                if ((this.ProductDescriptionField.Equals(value) != true)) {
                    this.ProductDescriptionField = value;
                    this.RaisePropertyChanged("ProductDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HypersWebApp.ServiceReference1.Product_Status Product_Status {
            get {
                return this.Product_StatusField;
            }
            set {
                if ((this.Product_StatusField.Equals(value) != true)) {
                    this.Product_StatusField = value;
                    this.RaisePropertyChanged("Product_Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long PurchasePrice {
            get {
                return this.PurchasePriceField;
            }
            set {
                if ((this.PurchasePriceField.Equals(value) != true)) {
                    this.PurchasePriceField = value;
                    this.RaisePropertyChanged("PurchasePrice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product_Description", Namespace="http://schemas.datacontract.org/2004/07/HypersWebshop.Domain")]
    public enum Product_Description : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Harddrive = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RAM = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Battery = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Power_Supply = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GPU = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CPU_Cooling = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Motherboard = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CPU = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Disk_Drive = 8,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product_Status", Namespace="http://schemas.datacontract.org/2004/07/HypersWebshop.Domain")]
    public enum Product_Status : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sold = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Published = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unpublished = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Tested = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Untested = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rejected = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeCustomer", Namespace="http://schemas.datacontract.org/2004/07/HypersWebshop.ServiceLib")]
    [System.SerializableAttribute()]
    public partial class CompositeCustomer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerPhoneNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerZipcodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerAddress {
            get {
                return this.CustomerAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerAddressField, value) != true)) {
                    this.CustomerAddressField = value;
                    this.RaisePropertyChanged("CustomerAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerCity {
            get {
                return this.CustomerCityField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerCityField, value) != true)) {
                    this.CustomerCityField = value;
                    this.RaisePropertyChanged("CustomerCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerEmail {
            get {
                return this.CustomerEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerEmailField, value) != true)) {
                    this.CustomerEmailField = value;
                    this.RaisePropertyChanged("CustomerEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerPhoneNo {
            get {
                return this.CustomerPhoneNoField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerPhoneNoField, value) != true)) {
                    this.CustomerPhoneNoField = value;
                    this.RaisePropertyChanged("CustomerPhoneNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerZipcode {
            get {
                return this.CustomerZipcodeField;
            }
            set {
                if ((this.CustomerZipcodeField.Equals(value) != true)) {
                    this.CustomerZipcodeField = value;
                    this.RaisePropertyChanged("CustomerZipcode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IProductService")]
    public interface IProductService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/UpdateProduct", ReplyAction="http://tempuri.org/IProductService/UpdateProductResponse")]
        void UpdateProduct(HypersWebApp.ServiceReference1.CompositeProduct composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/UpdateProduct", ReplyAction="http://tempuri.org/IProductService/UpdateProductResponse")]
        System.Threading.Tasks.Task UpdateProductAsync(HypersWebApp.ServiceReference1.CompositeProduct composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/CreateProduct", ReplyAction="http://tempuri.org/IProductService/CreateProductResponse")]
        int CreateProduct(HypersWebApp.ServiceReference1.CompositeProduct composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/CreateProduct", ReplyAction="http://tempuri.org/IProductService/CreateProductResponse")]
        System.Threading.Tasks.Task<int> CreateProductAsync(HypersWebApp.ServiceReference1.CompositeProduct composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/FindProduct", ReplyAction="http://tempuri.org/IProductService/FindProductResponse")]
        HypersWebApp.ServiceReference1.CompositeProduct FindProduct(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/FindProduct", ReplyAction="http://tempuri.org/IProductService/FindProductResponse")]
        System.Threading.Tasks.Task<HypersWebApp.ServiceReference1.CompositeProduct> FindProductAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/FindProductsByDescription", ReplyAction="http://tempuri.org/IProductService/FindProductsByDescriptionResponse")]
        System.Collections.Generic.List<HypersWebApp.ServiceReference1.CompositeProduct> FindProductsByDescription(HypersWebApp.ServiceReference1.Product_Description description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/FindProductsByDescription", ReplyAction="http://tempuri.org/IProductService/FindProductsByDescriptionResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<HypersWebApp.ServiceReference1.CompositeProduct>> FindProductsByDescriptionAsync(HypersWebApp.ServiceReference1.Product_Description description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/FindProductsByStatus", ReplyAction="http://tempuri.org/IProductService/FindProductsByStatusResponse")]
        System.Collections.Generic.List<HypersWebApp.ServiceReference1.CompositeProduct> FindProductsByStatus(HypersWebApp.ServiceReference1.Product_Status status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/FindProductsByStatus", ReplyAction="http://tempuri.org/IProductService/FindProductsByStatusResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<HypersWebApp.ServiceReference1.CompositeProduct>> FindProductsByStatusAsync(HypersWebApp.ServiceReference1.Product_Status status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/CreateCustomer", ReplyAction="http://tempuri.org/IProductService/CreateCustomerResponse")]
        void CreateCustomer(HypersWebApp.ServiceReference1.CompositeCustomer composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/CreateCustomer", ReplyAction="http://tempuri.org/IProductService/CreateCustomerResponse")]
        System.Threading.Tasks.Task CreateCustomerAsync(HypersWebApp.ServiceReference1.CompositeCustomer composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/ProcessSale", ReplyAction="http://tempuri.org/IProductService/ProcessSaleResponse")]
        string ProcessSale(System.Collections.Generic.List<HypersWebApp.ServiceReference1.CompositeProduct> compProducts, HypersWebApp.ServiceReference1.CompositeCustomer compCustomer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductService/ProcessSale", ReplyAction="http://tempuri.org/IProductService/ProcessSaleResponse")]
        System.Threading.Tasks.Task<string> ProcessSaleAsync(System.Collections.Generic.List<HypersWebApp.ServiceReference1.CompositeProduct> compProducts, HypersWebApp.ServiceReference1.CompositeCustomer compCustomer);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductServiceChannel : HypersWebApp.ServiceReference1.IProductService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductServiceClient : System.ServiceModel.ClientBase<HypersWebApp.ServiceReference1.IProductService>, HypersWebApp.ServiceReference1.IProductService {
        
        public ProductServiceClient() {
        }
        
        public ProductServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void UpdateProduct(HypersWebApp.ServiceReference1.CompositeProduct composite) {
            base.Channel.UpdateProduct(composite);
        }
        
        public System.Threading.Tasks.Task UpdateProductAsync(HypersWebApp.ServiceReference1.CompositeProduct composite) {
            return base.Channel.UpdateProductAsync(composite);
        }
        
        public int CreateProduct(HypersWebApp.ServiceReference1.CompositeProduct composite) {
            return base.Channel.CreateProduct(composite);
        }
        
        public System.Threading.Tasks.Task<int> CreateProductAsync(HypersWebApp.ServiceReference1.CompositeProduct composite) {
            return base.Channel.CreateProductAsync(composite);
        }
        
        public HypersWebApp.ServiceReference1.CompositeProduct FindProduct(int id) {
            return base.Channel.FindProduct(id);
        }
        
        public System.Threading.Tasks.Task<HypersWebApp.ServiceReference1.CompositeProduct> FindProductAsync(int id) {
            return base.Channel.FindProductAsync(id);
        }
        
        public System.Collections.Generic.List<HypersWebApp.ServiceReference1.CompositeProduct> FindProductsByDescription(HypersWebApp.ServiceReference1.Product_Description description) {
            return base.Channel.FindProductsByDescription(description);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<HypersWebApp.ServiceReference1.CompositeProduct>> FindProductsByDescriptionAsync(HypersWebApp.ServiceReference1.Product_Description description) {
            return base.Channel.FindProductsByDescriptionAsync(description);
        }
        
        public System.Collections.Generic.List<HypersWebApp.ServiceReference1.CompositeProduct> FindProductsByStatus(HypersWebApp.ServiceReference1.Product_Status status) {
            return base.Channel.FindProductsByStatus(status);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<HypersWebApp.ServiceReference1.CompositeProduct>> FindProductsByStatusAsync(HypersWebApp.ServiceReference1.Product_Status status) {
            return base.Channel.FindProductsByStatusAsync(status);
        }
        
        public void CreateCustomer(HypersWebApp.ServiceReference1.CompositeCustomer composite) {
            base.Channel.CreateCustomer(composite);
        }
        
        public System.Threading.Tasks.Task CreateCustomerAsync(HypersWebApp.ServiceReference1.CompositeCustomer composite) {
            return base.Channel.CreateCustomerAsync(composite);
        }
        
        public string ProcessSale(System.Collections.Generic.List<HypersWebApp.ServiceReference1.CompositeProduct> compProducts, HypersWebApp.ServiceReference1.CompositeCustomer compCustomer) {
            return base.Channel.ProcessSale(compProducts, compCustomer);
        }
        
        public System.Threading.Tasks.Task<string> ProcessSaleAsync(System.Collections.Generic.List<HypersWebApp.ServiceReference1.CompositeProduct> compProducts, HypersWebApp.ServiceReference1.CompositeCustomer compCustomer) {
            return base.Channel.ProcessSaleAsync(compProducts, compCustomer);
        }
    }
}
