//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HypersWebshop.DTTestTab.ServiceReference2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/HypersWebshop.ServiceLib")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.ITestInterface")]
    public interface ITestInterface {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestInterface/TestMethod", ReplyAction="http://tempuri.org/ITestInterface/TestMethodResponse")]
        System.DateTime TestMethod();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestInterface/TestMethod", ReplyAction="http://tempuri.org/ITestInterface/TestMethodResponse")]
        System.Threading.Tasks.Task<System.DateTime> TestMethodAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestInterface/GetData", ReplyAction="http://tempuri.org/ITestInterface/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestInterface/GetData", ReplyAction="http://tempuri.org/ITestInterface/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestInterface/GetDataUsingDataContract", ReplyAction="http://tempuri.org/ITestInterface/GetDataUsingDataContractResponse")]
        HypersWebshop.DTTestTab.ServiceReference2.CompositeType GetDataUsingDataContract(HypersWebshop.DTTestTab.ServiceReference2.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestInterface/GetDataUsingDataContract", ReplyAction="http://tempuri.org/ITestInterface/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<HypersWebshop.DTTestTab.ServiceReference2.CompositeType> GetDataUsingDataContractAsync(HypersWebshop.DTTestTab.ServiceReference2.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITestInterfaceChannel : HypersWebshop.DTTestTab.ServiceReference2.ITestInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TestInterfaceClient : System.ServiceModel.ClientBase<HypersWebshop.DTTestTab.ServiceReference2.ITestInterface>, HypersWebshop.DTTestTab.ServiceReference2.ITestInterface {
        
        public TestInterfaceClient() {
        }
        
        public TestInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TestInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.DateTime TestMethod() {
            return base.Channel.TestMethod();
        }
        
        public System.Threading.Tasks.Task<System.DateTime> TestMethodAsync() {
            return base.Channel.TestMethodAsync();
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public HypersWebshop.DTTestTab.ServiceReference2.CompositeType GetDataUsingDataContract(HypersWebshop.DTTestTab.ServiceReference2.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<HypersWebshop.DTTestTab.ServiceReference2.CompositeType> GetDataUsingDataContractAsync(HypersWebshop.DTTestTab.ServiceReference2.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
